name: Setup
inputs:
  dioxus-cli-version:
    required: true
  vcpkg-version:
    required: true
  vcpkg-root:
    required: true
  protoc-version:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: cache-vcpkg
      with:
        path: ${{ inputs.vcpkg-root }}
        key: vcpkg-${{ inputs.vcpkg-version }}

    - if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        git clone https://github.com/Microsoft/vcpkg.git "${{ inputs.vcpkg-root }}"
        cd "${{ inputs.vcpkg-root }}"
        git fetch --all --prune --tags
        git status
        git checkout .
        git checkout "${{ inputs.vcpkg-version }}"
        ./bootstrap-vcpkg.bat -disableMetrics
        echo "set(VCPKG_BUILD_TYPE release)" >> triplets/x64-windows.cmake
        echo "set(VCPKG_BUILD_TYPE release)" >> triplets/x64-windows-static.cmake
        ./vcpkg.exe install --clean-after-build --recurse opencv4[contrib,nonfree]:x64-windows-static

    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: "npm"
        cache-dependency-path: "./ui/package-lock.json"
    - name: Install TailwindCSS and Dioxus CLI
      shell: pwsh
      run: |
        cd ui
        npm install

    - uses: mozilla-actions/sccache-action@v0.0.9

    - uses: cargo-bins/cargo-binstall@main
    - name: Install Dioxus CLI
      shell: pwsh
      run: cargo binstall dioxus-cli@${{ inputs.dioxus-cli-version }} --no-confirm

    - name: Install protoc
      shell: pwsh
      run: choco install -y protoc --version "${{ inputs.protoc-version }}"
